#!/usr/bin/env python3
"""Build an INT8 engine calibrated with real obs on Jetson (native TRT PTQ) — the PPO navigation engine.

Calibration data is generated by the PC-side `onnx/export_ppo_onnx.py --make-calib`
(calib_obs.npz, key='obs', shape (N, obs_dim), obs_dim = 105 (N=1) or 113 (N=5)).

Navigation always uses batch=1 engines (--batch-size 1 is mandatory; a bs8 engine's forward size mismatch will stop the robot).

Usage (on board, any directory):
    python3 build_ptq_engine.py --onnx actor_fp32_bs1.onnx \
        --calib calib_obs.npz --out actor_int8.engine --batch-size 1
"""

import argparse
import ctypes
import ctypes.util
import os
import sys
import traceback

import numpy as np
import tensorrt as trt

TRT_LOGGER = trt.Logger(trt.Logger.WARNING)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

VERBOSE = False

CUDA_MEMCPY_HOST_TO_DEVICE = 1
_CUDART = None


def _load_cudart():
    """Load the CUDA runtime for cudaMalloc / cudaMemcpy / cudaFree.

    The calibrator's get_batch must return device (GPU) memory pointers; returning host pointers causes
    "illegal memory access" (TRT reads/writes the bindings directly as CUDA pointers).
    """
    global _CUDART
    if _CUDART is not None:
        return _CUDART
    names = []
    found = ctypes.util.find_library("cudart")
    if found:
        names.append(found)
    names += ["libcudart.so", "libcudart.so.12", "libcudart.so.11", "libcudart.so.8"]
    for n in names:
        try:
            _CUDART = ctypes.CDLL(n)
            break
        except OSError:
            continue
    if _CUDART is None:
        raise SystemExit("[PTQ] failed to load libcudart (please confirm the CUDA runtime is installed)")
    _CUDART.cudaMalloc.argtypes = [ctypes.POINTER(ctypes.c_void_p), ctypes.c_size_t]
    _CUDART.cudaMalloc.restype = ctypes.c_int
    _CUDART.cudaMemcpy.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_int]
    _CUDART.cudaMemcpy.restype = ctypes.c_int
    _CUDART.cudaFree.argtypes = [ctypes.c_void_p]
    _CUDART.cudaFree.restype = ctypes.c_int
    return _CUDART


def log(msg: str) -> None:
    if VERBOSE:
        print(f"[DBG] {msg}", flush=True)


class ObsCalibrator(trt.IInt8EntropyCalibrator2):
    """Feed the in-memory obs array to EntropyCalibrator2 in batches.

    Note: IInt8EntropyCalibrator2 is used as the base class (ICalibrator is not exported by the tensorrt python bindings).
    """

    def __init__(self, obs: np.ndarray, batch_size: int = 1, cache: str = "calib.cache"):
        super().__init__()
        self.obs = np.ascontiguousarray(obs, dtype=np.float32)  # (N, obs_dim)
        self.batch_size = int(batch_size)
        self.pos = 0
        self.cache_path = cache
        self._cache = None
        self._last_batch = None
        self._calls = 0
        self._dev_ptr = None
        self._dev_nbytes = self.batch_size * self.obs.shape[1] * self.obs.itemsize

        cudart = _load_cudart()
        dev_ptr = ctypes.c_void_p()
        err = cudart.cudaMalloc(ctypes.byref(dev_ptr), self._dev_nbytes)
        if err != 0:
            raise SystemExit(f"[PTQ] cudaMalloc failed: err={err}")
        self._dev_ptr = int(dev_ptr.value)

        print(
            f"[DBG] calibrator init: obs.shape={self.obs.shape} dtype={self.obs.dtype} "
            f"batch_size={self.batch_size} cache_exists={os.path.exists(cache)} "
            f"device_buf={hex(self._dev_ptr)} ({self._dev_nbytes} bytes)",
            flush=True,
        )
        if os.path.exists(cache):
            with open(cache, "rb") as f:
                self._cache = f.read()
            log(f"read cache {len(self._cache)} bytes")

    def free(self) -> None:
        if self._dev_ptr is not None:
            cudart = _load_cudart()
            cudart.cudaFree(ctypes.c_void_p(self._dev_ptr))
            self._dev_ptr = None
            log("cudaFree device buffer")

    def get_batch_size(self) -> int:
        log(f"get_batch_size -> {self.batch_size}")
        return self.batch_size

    def get_batch(self, names):
        self._calls += 1
        log(f"get_batch #{self._calls}: names={names!r} pos={self.pos}/{len(self.obs)}")
        if self.pos >= len(self.obs):
            log("  -> None (EOF)")
            return None
        batch = self.obs[self.pos:self.pos + self.batch_size]
        self.pos += self.batch_size
        log(
            f"  slice shape={batch.shape} dtype={batch.dtype} "
            f"c_contig={batch.flags['C_CONTIGUOUS']}"
        )
        try:
            # must be a C-contiguous, explicitly copied array (not GC'd, see self._last_batch).
            arr = np.array(batch, dtype=np.float32, copy=True, order="C")
            log(
                f"  arr shape={arr.shape} dtype={arr.dtype} "
                f"c_contig={arr.flags['C_CONTIGUOUS']} id={hex(id(arr))}"
            )
        except Exception:
            print("[DBG] failed to create a numpy array inside get_batch:", flush=True)
            traceback.print_exc()
            return None

        # The TRT 8.x python binding trampoline (pyInt8.cpp:58-64) requires get_batch to
        # return an integer list of "the data memory pointer for each input"
        # (std::vector<size_t>), which is memcpy'd directly into void* bindings.
        # Returning the numpy array itself makes the pybind cast numpy->size_t fail:
        #   "Exception caught in get_batch(): Unable to cast Python instance to C++ type".
        #
        # Also, the pointer MUST be a DEVICE (GPU) memory pointer: calibration actually runs the
        # network on the GPU, and stuffing a host pointer into bindings triggers "illegal memory access".
        # Here we copy the host data into a pre-allocated cudaMalloc buffer and return its device pointer.
        n_in = max(1, len(names))
        self._last_batch = [arr] * n_in
        cudart = _load_cudart()
        err = cudart.cudaMemcpy(
            ctypes.c_void_p(self._dev_ptr),
            arr.ctypes.data_as(ctypes.c_void_p),
            arr.nbytes,  # the last batch may be smaller than batch_size; use the actual byte count to avoid OOB reads
            CUDA_MEMCPY_HOST_TO_DEVICE,
        )
        if err != 0:
            print(f"[DBG] cudaMemcpy H2D failed: err={err}", flush=True)
            return None
        ptrs = [self._dev_ptr] * n_in
        log(f"  -> returning device pointer list len={n_in} ptrs={[hex(p) for p in ptrs]}")
        return ptrs

    def read_calibration_cache(self):
        log(f"read_calibration_cache -> {0 if self._cache is None else len(self._cache)} bytes")
        return self._cache

    def write_calibration_cache(self, buf) -> None:
        log(f"write_calibration_cache: {len(buf)} bytes -> {self.cache_path}")
        with open(self.cache_path, "wb") as f:
            f.write(buf)


def build_engine(onnx_path: str, obs: np.ndarray, out_path: str,
                 batch_size: int = 1, cache: str = "calib.cache") -> None:
    print(f"[DBG] python: {sys.version.split()[0]}", flush=True)
    print(f"[DBG] numpy : {np.__version__}", flush=True)
    print(f"[DBG] trt   : {trt.__version__}", flush=True)

    builder = trt.Builder(TRT_LOGGER)
    network = builder.create_network(
        1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )
    parser = trt.OnnxParser(network, TRT_LOGGER)
    with open(onnx_path, "rb") as f:
        if not parser.parse(f.read()):
            for i in range(parser.num_errors):
                print(parser.get_error(i))
            raise SystemExit(f"[PTQ] onnx parse failed: {onnx_path}")
    print("[DBG] onnx parsed successfully", flush=True)

    config = builder.create_builder_config()
    config.set_flag(trt.BuilderFlag.INT8)
    calibrator = ObsCalibrator(obs, batch_size=batch_size, cache=cache)
    config.int8_calibrator = calibrator
    try:
        config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)
    except AttributeError:  # older TRT versions
        config.max_workspace_size = 1 << 30

    for i in range(network.num_inputs):
        d = network.get_input(i).shape
        print(f"[PTQ] network input '{network.get_input(i).name}': {list(d)}", flush=True)

    print("[DBG] calling build_serialized_network ...", flush=True)
    serialized = None
    try:
        serialized = builder.build_serialized_network(network, config)
    except Exception as e:
        print(f"[PTQ] build_serialized_network threw: {type(e).__name__}: {e}", flush=True)
        traceback.print_exc()
    print(f"[DBG] build_serialized_network returned: {serialized!r}", flush=True)

    if serialized is None:
        print("[DBG] trying fallback builder.build_engine() ...", flush=True)
        try:
            serialized = builder.build_engine(network, config)
            print(f"[DBG] build_engine returned: {serialized!r}", flush=True)
        except Exception as e2:
            print(f"[PTQ] build_engine also threw: {type(e2).__name__}: {e2}", flush=True)
            traceback.print_exc()

    if serialized is None:
        calibrator.free()
        raise SystemExit(
            "[PTQ] INT8 engine build failed (both APIs returned None / threw). "
            f"get_batch was called {calibrator._calls} times. "
        )

    with open(out_path, "wb") as f:
        f.write(serialized)
    print(f"[PTQ] INT8 engine saved to {out_path}")

    calibrator.free()


def main() -> None:
    ap = argparse.ArgumentParser(description="TRT INT8 real-data calibration (PTQ) — PPO navigation engine")
    ap.add_argument("--onnx", default=None, help="FP32 ONNX (default <this dir>/actor_fp32_bs1.onnx)")
    ap.add_argument("--calib", default=None, help="calibration data npz (default <this dir>/calib_obs.npz)")
    ap.add_argument("--out", default=None, help="output INT8 engine (default <this dir>/actor_int8.engine)")
    ap.add_argument("--batch-size", type=int, default=1,
                    help="calibration batch (navigation always uses 1; a bs8 engine's forward size mismatch will stop the robot)")
    ap.add_argument("--cache", default=None, help="calibration cache (default <this dir>/calib.cache)")
    ap.add_argument("--verbose", action="store_true", help="print detailed calibration callback logs")
    args = ap.parse_args()

    global VERBOSE
    VERBOSE = args.verbose

    onnx_path = args.onnx or os.path.join(SCRIPT_DIR, "actor_fp32_bs1.onnx")
    calib_path = args.calib or os.path.join(SCRIPT_DIR, "calib_obs.npz")
    out_path = args.out or os.path.join(SCRIPT_DIR, "actor_int8.engine")
    cache_path = args.cache or os.path.join(SCRIPT_DIR, "calib.cache")

    if not os.path.exists(onnx_path):
        raise SystemExit(f"[PTQ] onnx does not exist: {onnx_path}")
    if not os.path.exists(calib_path):
        raise SystemExit(
            f"[PTQ] calibration data does not exist: {calib_path} (run onnx/export_ppo_onnx.py --make-calib on the PC first)"
        )

    obs = np.load(calib_path)["obs"]
    print(f"[PTQ] calib obs: {obs.shape} ({obs.shape[0]} samples)")
    build_engine(onnx_path, obs, out_path, args.batch_size, cache_path)


if __name__ == "__main__":
    main()
